/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShareId = IDL.Nat;
export const FileId = IDL.Nat;
export const SharePermission = IDL.Variant({
  'view' : IDL.Null,
  'download' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const ShareView = IDL.Record({
  'id' : ShareId,
  'permission' : SharePermission,
  'expiresAt' : IDL.Opt(Timestamp),
  'revoked' : IDL.Bool,
  'owner' : IDL.Principal,
  'createdAt' : Timestamp,
  'shareToken' : IDL.Text,
  'decryptionKey' : IDL.Text,
  'sharedWith' : IDL.Principal,
  'fileId' : FileId,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DownloadResult = IDL.Record({
  'blob' : ExternalBlob,
  'sha256Hash' : IDL.Text,
  'decryptionKey' : IDL.Opt(IDL.Text),
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const AuditAction = IDL.Variant({
  'unauthorizedAccess' : IDL.Null,
  'linkCreate' : IDL.Null,
  'failedLogin' : IDL.Null,
  'logout' : IDL.Null,
  'delete' : IDL.Null,
  'login' : IDL.Null,
  'share' : IDL.Null,
  'upload' : IDL.Null,
  'download' : IDL.Null,
  'linkRevoke' : IDL.Null,
});
export const AuditLog = IDL.Record({
  'id' : IDL.Nat,
  'action' : AuditAction,
  'userId' : IDL.Principal,
  'fileId' : IDL.Opt(IDL.Nat),
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
  'ipAddress' : IDL.Text,
});
export const AccountStatus = IDL.Variant({
  'active' : IDL.Null,
  'deactivated' : IDL.Null,
});
export const User = IDL.Record({
  'status' : AccountStatus,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'passwordHash' : IDL.Text,
});
export const FailedLogin__1 = IDL.Record({
  'id' : IDL.Nat,
  'email' : IDL.Text,
  'attemptedAt' : IDL.Int,
  'ipAddress' : IDL.Text,
});
export const FileView = IDL.Record({
  'id' : FileId,
  'originalFilename' : IDL.Text,
  'sha256Hash' : IDL.Text,
  'mimeType' : IDL.Text,
  'fileSize' : IDL.Nat,
  'storedFilename' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const FailedLogin = IDL.Record({
  'email' : IDL.Text,
  'attemptedAt' : IDL.Int,
});
export const AuthError = IDL.Variant({
  'accountDeactivated' : IDL.Null,
  'emailTaken' : IDL.Null,
  'weakPassword' : IDL.Null,
  'notRegistered' : IDL.Null,
  'unauthorized' : IDL.Null,
  'invalidCredentials' : IDL.Null,
});
export const Result_1 = IDL.Variant({ 'ok' : User, 'err' : AuthError });
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError });

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_2], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkDownloadAccess' : IDL.Func([ShareId], [IDL.Bool], ['query']),
  'createShare' : IDL.Func(
      [FileId, IDL.Principal, SharePermission, IDL.Opt(Timestamp), IDL.Text],
      [ShareView],
      [],
    ),
  'deleteFile' : IDL.Func([FileId], [IDL.Bool], []),
  'downloadFile' : IDL.Func([FileId], [IDL.Opt(DownloadResult)], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'getAllLogs' : IDL.Func([], [IDL.Vec(AuditLog)], []),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFailedLogins' : IDL.Func([], [IDL.Vec(FailedLogin__1)], []),
  'getMyActivity' : IDL.Func([], [IDL.Vec(AuditLog)], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllFiles' : IDL.Func([], [IDL.Vec(FileView)], ['query']),
  'listAllShares' : IDL.Func([], [IDL.Vec(ShareView)], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'listFailedLogins' : IDL.Func([], [IDL.Vec(FailedLogin)], ['query']),
  'listMyFiles' : IDL.Func([], [IDL.Vec(FileView)], ['query']),
  'listOwnerShares' : IDL.Func([], [IDL.Vec(ShareView)], ['query']),
  'listSharesForUser' : IDL.Func([], [IDL.Vec(ShareView)], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'logout' : IDL.Func([], [], []),
  'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_1], []),
  'revokeShare' : IDL.Func([ShareId], [IDL.Bool], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setAccountStatus' : IDL.Func([IDL.Principal, AccountStatus], [Result], []),
  'uploadFile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, ExternalBlob],
      [FileView],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShareId = IDL.Nat;
  const FileId = IDL.Nat;
  const SharePermission = IDL.Variant({
    'view' : IDL.Null,
    'download' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const ShareView = IDL.Record({
    'id' : ShareId,
    'permission' : SharePermission,
    'expiresAt' : IDL.Opt(Timestamp),
    'revoked' : IDL.Bool,
    'owner' : IDL.Principal,
    'createdAt' : Timestamp,
    'shareToken' : IDL.Text,
    'decryptionKey' : IDL.Text,
    'sharedWith' : IDL.Principal,
    'fileId' : FileId,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DownloadResult = IDL.Record({
    'blob' : ExternalBlob,
    'sha256Hash' : IDL.Text,
    'decryptionKey' : IDL.Opt(IDL.Text),
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const AuditAction = IDL.Variant({
    'unauthorizedAccess' : IDL.Null,
    'linkCreate' : IDL.Null,
    'failedLogin' : IDL.Null,
    'logout' : IDL.Null,
    'delete' : IDL.Null,
    'login' : IDL.Null,
    'share' : IDL.Null,
    'upload' : IDL.Null,
    'download' : IDL.Null,
    'linkRevoke' : IDL.Null,
  });
  const AuditLog = IDL.Record({
    'id' : IDL.Nat,
    'action' : AuditAction,
    'userId' : IDL.Principal,
    'fileId' : IDL.Opt(IDL.Nat),
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
    'ipAddress' : IDL.Text,
  });
  const AccountStatus = IDL.Variant({
    'active' : IDL.Null,
    'deactivated' : IDL.Null,
  });
  const User = IDL.Record({
    'status' : AccountStatus,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'passwordHash' : IDL.Text,
  });
  const FailedLogin__1 = IDL.Record({
    'id' : IDL.Nat,
    'email' : IDL.Text,
    'attemptedAt' : IDL.Int,
    'ipAddress' : IDL.Text,
  });
  const FileView = IDL.Record({
    'id' : FileId,
    'originalFilename' : IDL.Text,
    'sha256Hash' : IDL.Text,
    'mimeType' : IDL.Text,
    'fileSize' : IDL.Nat,
    'storedFilename' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const FailedLogin = IDL.Record({
    'email' : IDL.Text,
    'attemptedAt' : IDL.Int,
  });
  const AuthError = IDL.Variant({
    'accountDeactivated' : IDL.Null,
    'emailTaken' : IDL.Null,
    'weakPassword' : IDL.Null,
    'notRegistered' : IDL.Null,
    'unauthorized' : IDL.Null,
    'invalidCredentials' : IDL.Null,
  });
  const Result_1 = IDL.Variant({ 'ok' : User, 'err' : AuthError });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_2], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkDownloadAccess' : IDL.Func([ShareId], [IDL.Bool], ['query']),
    'createShare' : IDL.Func(
        [FileId, IDL.Principal, SharePermission, IDL.Opt(Timestamp), IDL.Text],
        [ShareView],
        [],
      ),
    'deleteFile' : IDL.Func([FileId], [IDL.Bool], []),
    'downloadFile' : IDL.Func([FileId], [IDL.Opt(DownloadResult)], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'getAllLogs' : IDL.Func([], [IDL.Vec(AuditLog)], []),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFailedLogins' : IDL.Func([], [IDL.Vec(FailedLogin__1)], []),
    'getMyActivity' : IDL.Func([], [IDL.Vec(AuditLog)], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllFiles' : IDL.Func([], [IDL.Vec(FileView)], ['query']),
    'listAllShares' : IDL.Func([], [IDL.Vec(ShareView)], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'listFailedLogins' : IDL.Func([], [IDL.Vec(FailedLogin)], ['query']),
    'listMyFiles' : IDL.Func([], [IDL.Vec(FileView)], ['query']),
    'listOwnerShares' : IDL.Func([], [IDL.Vec(ShareView)], ['query']),
    'listSharesForUser' : IDL.Func([], [IDL.Vec(ShareView)], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'logout' : IDL.Func([], [], []),
    'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_1], []),
    'revokeShare' : IDL.Func([ShareId], [IDL.Bool], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setAccountStatus' : IDL.Func([IDL.Principal, AccountStatus], [Result], []),
    'uploadFile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, ExternalBlob],
        [FileView],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };