/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountStatus = { 'active' : null } |
  { 'deactivated' : null };
export type AuditAction = { 'unauthorizedAccess' : null } |
  { 'linkCreate' : null } |
  { 'failedLogin' : null } |
  { 'logout' : null } |
  { 'delete' : null } |
  { 'login' : null } |
  { 'share' : null } |
  { 'upload' : null } |
  { 'download' : null } |
  { 'linkRevoke' : null };
export interface AuditLog {
  'id' : bigint,
  'action' : AuditAction,
  'userId' : Principal,
  'fileId' : [] | [bigint],
  'timestamp' : bigint,
  'details' : string,
  'ipAddress' : string,
}
export type AuthError = { 'accountDeactivated' : null } |
  { 'emailTaken' : null } |
  { 'weakPassword' : null } |
  { 'notRegistered' : null } |
  { 'unauthorized' : null } |
  { 'invalidCredentials' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface DownloadResult {
  'blob' : ExternalBlob,
  'sha256Hash' : string,
  'decryptionKey' : [] | [string],
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export interface FailedLogin { 'email' : string, 'attemptedAt' : bigint }
export interface FailedLogin__1 {
  'id' : bigint,
  'email' : string,
  'attemptedAt' : bigint,
  'ipAddress' : string,
}
export type FileId = bigint;
export interface FileView {
  'id' : FileId,
  'originalFilename' : string,
  'sha256Hash' : string,
  'mimeType' : string,
  'fileSize' : bigint,
  'storedFilename' : string,
  'uploadedAt' : bigint,
}
export type Result = { 'ok' : null } |
  { 'err' : AuthError };
export type Result_1 = { 'ok' : User } |
  { 'err' : AuthError };
export type Result_2 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type ShareId = bigint;
export type SharePermission = { 'view' : null } |
  { 'download' : null };
export interface ShareView {
  'id' : ShareId,
  'permission' : SharePermission,
  'expiresAt' : [] | [Timestamp],
  'revoked' : boolean,
  'owner' : Principal,
  'createdAt' : Timestamp,
  'shareToken' : string,
  'decryptionKey' : string,
  'sharedWith' : Principal,
  'fileId' : FileId,
}
export type Timestamp = bigint;
export interface User {
  'status' : AccountStatus,
  'principal' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'passwordHash' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_2>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkDownloadAccess' : ActorMethod<[ShareId], boolean>,
  'createShare' : ActorMethod<
    [FileId, Principal, SharePermission, [] | [Timestamp], string],
    ShareView
  >,
  'deleteFile' : ActorMethod<[FileId], boolean>,
  'downloadFile' : ActorMethod<[FileId], [] | [DownloadResult]>,
  'execute' : ActorMethod<[string], Result__1>,
  'getAllLogs' : ActorMethod<[], Array<AuditLog>>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUser' : ActorMethod<[], [] | [User]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFailedLogins' : ActorMethod<[], Array<FailedLogin__1>>,
  'getMyActivity' : ActorMethod<[], Array<AuditLog>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllFiles' : ActorMethod<[], Array<FileView>>,
  'listAllShares' : ActorMethod<[], Array<ShareView>>,
  'listAllUsers' : ActorMethod<[], Array<User>>,
  'listFailedLogins' : ActorMethod<[], Array<FailedLogin>>,
  'listMyFiles' : ActorMethod<[], Array<FileView>>,
  'listOwnerShares' : ActorMethod<[], Array<ShareView>>,
  'listSharesForUser' : ActorMethod<[], Array<ShareView>>,
  'login' : ActorMethod<[string, string], Result_1>,
  'logout' : ActorMethod<[], undefined>,
  'register' : ActorMethod<[string, string, string], Result_1>,
  'revokeShare' : ActorMethod<[ShareId], boolean>,
  'schema' : ActorMethod<[], string>,
  'setAccountStatus' : ActorMethod<[Principal, AccountStatus], Result>,
  'uploadFile' : ActorMethod<
    [string, string, string, bigint, string, ExternalBlob],
    FileView
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];